# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "mt7921e" ];
  boot.extraModprobeConfig = ''
    options mt7921e disable_aspm=1
  '';
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "pcie_aspm=off" ];
  boot.kernelPackages = pkgs.linuxPackages_zen;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1188c698-d8a5-463b-9f4a-fd15a3ccfd03";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FF1A-290E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
