[config]
reload_apps = false

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf.template"
output_path = "/tmp/kitty-matugen-colors.conf"

[templates.discord]
input_path = "~/.config/matugen/templates/discord.css.template"
output_path = "~/.config/vesktop/themes/matugen.theme.css"

[templates.firefox]
input_path = "~/.config/matugen/templates/firefox.css"
output_path = "~/.mozilla/firefox/zawmoi9h.default/chrome/matugen.css"

[templates.web_github]
input_path = "~/.config/matugen/templates/websites/github.css.template"
output_path = "~/.mozilla/firefox/zawmoi9h.default/chrome/matugen-github.css"

[templates.web_youtube]
input_path = "~/.config/matugen/templates/websites/youtube.css.template"
output_path = "~/.mozilla/firefox/zawmoi9h.default/chrome/matugen-youtube.css"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi.template"
output_path = "~/.config/rofi/theme.rasi"